version: '2.1'
orbs:
  maven: circleci/maven@1.4.0
executors:
  machine_executor_amd64:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
workflows:
  maven_test:
    jobs:
      - maven/test:
          executor:
            name: machine_executor_amd64
            tag: 17.0
