version: '3.8'
services:
  bookstore:
    #image: sivaprasadreddy/bookstore
    build: ..
    container_name: bookstore
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bookstore-postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATA_REDIS_HOST=bookstore-redis
      - SPRING_DATA_REDIS_PORT=6379
      - KAFKA_BROKER=kafka:9092
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - bookstore-postgres
      - bookstore-redis
      - kafka
    profiles:
      - app

  bookstore-postgres:
    image: postgres:15.4-alpine
    container_name: bookstore-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  bookstore-redis:
    image: redis:7.2.0-alpine
    container_name: bookstore-redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    restart: unless-stopped

#  redis-commander:
#    image: rediscommander/redis-commander:latest
#    container_name: redis-commander
#    hostname: redis-commander
#    restart: always
#    environment:
#      - REDIS_HOSTS=local:bookstore-redis:6379
#    ports:
#      - "9081:8081"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9101:9101"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
    volumes:
        - ./run_workaround.sh:/tmp/run_workaround.sh
    command: "bash -c '/tmp/run_workaround.sh && /etc/confluent/docker/run'"
