apiVersion: v1
kind: ConfigMap
metadata:
  name: bookstore-configmap
  namespace: default
data:
  postgres_host: "bookstore-postgres-svc"
  postgres_port: "5432"
  postgres_database: "bookstoredb"
  redis_host: "bookstore-redis-svc"
  redis_port: "6379"
---
apiVersion: v1
kind: Secret
metadata:
  name: bookstore-secrets
type: Opaque
data:
  postgres_username: c2l2YQ== # siva
  postgres_password: c2l2YWxhYnM= # sivalabs
