name: CI Build

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Maven Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./bookstore
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Make Maven wrapper executable
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw -ntp verify
